### ISSUE TITLE
Fix for Active Transport and FCV causing crash

### ISSUE THREAD

**Issue by osundwajeff** [kartoza/GEEST#132]
Fixes and testing for Fiji and Tunisa datasets crashing under Factors: Active Transport and FCV.

These two factors depend on generation of a 100m by 100m grid, which were initially in memory causing the crash as highlighted in issue #55 and #42, #45, #47, #50

**Comment by mvmaltitz** [comment]
@timlinux 
Active Transport still gives a problem, but FCV was working on my side (after @bennyistanto tested) it eventually crashes on my side.

Michelle error:
![image](https://github.com/user-attachments/assets/24c4b099-25a2-429c-b756-10d71322355d)

Benny feedback:
Active Transport is not responding without any error information, not long after pressing the Execute button

![Screenshot 2024-09-12 202600](https://github.com/user-attachments/assets/34a4614d-28e3-44db-80bf-870426bcbace)

Please see #134 and #135 for full testing results and input data
