### ISSUE TITLE
End-to-end User Testing

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST#135]
The following needs to be tested:

## 1. Contextual
**Workplace Discrimination:** 
- Test that the _WD_ raster is correctly generated

**Regulatory Frameworks**
- Test that the _RF_ raster is correctly generated

**Financial Inclusion**
- Test that the _FIN_ raster is correctly generated

**Aggregate**
- Test that the _Contextual_score_ raster is correctly generated

## 2. Accessibility
**Woman's Travel Patterns**
- Test that the _Green Spaces_ raster is correctly generated
- Test that the _Grocery Stores_ raster is correctly generated
- Test that the _Pharmacies_ raster is correctly generated
- Test that the _Kindergaten or Primary Schools_ raster is correctly generated
- Test that the _WTP_ raster is correctly generated

**Public Transport**
- Test that the _PBT_ raster is correctly generated

**Education and Training Facilities**
- Test that the _EFT_ raster is correctly generated

**Health Facilities**
- Test that the _HEF_ raster is correctly generated

**Financial Facilities**
- Test that the _FIF_ raster is correctly generated

**Aggregate**
- Test that the _Accessibility_score_ raster is correctly generated

## 3. Place Characterization
**Active Transport**
- Test that the _Crosswalks_ raster is correctly generated
- Test that the _Cycle Paths_ raster is correctly generated
- Test that the _Pathways_ raster is correctly generated
- Test that the _Block_ raster is correctly generated
- Test that the _AT_ raster is correctly generated

**Safety**
- Test that the _SAF_ raster is correctly generated using a point input
- Test that the _SAF_ raster is correctly generated using a polygon input
- Test that the _SAF_ raster is correctly generated using a raster input
- Test that the _SAF_ raster is correctly generated using a perceived safety value input

**Digital Inclusion**
- Test that the _DIG_ raster is correctly generated using the field of interest option
- Test that the _DIG_ raster is correctly generated using an internet access value

**Environmental Hazards**
- Test that the _Fire_ raster is correctly generated
- Test that the _Flood_ raster is correctly generated
- Test that the _Landslide_ raster is correctly generated
- Test that the _Tropical Cyclone_ raster is correctly generated
- Test that the _Drought_ raster is correctly generated
- Test that the _ENV_ raster is correctly generated

**Education**
- Test that the _EDU_ raster is correctly generated using the field of interest option
- Test that the _EDU_ raster is correctly generated using an education value

**FCV**
- Test that the _FCV_ raster is correctly generated using just the CSV input file with no impact radius
- Test that the _FCV_ raster is correctly generated using the CSV input file with impact radius

**Water Sanitation**
- Test that the _WAS_ raster is correctly generated 

**Aggregate**
- Test that the _Place_score_ raster is correctly generated

## 4. Aggregate
- Test that the _WEE_ raster is correctly generated

## 5. Insights
**Enablement**
- Test that the _WEE_pop_adm_score_ raster is correctly generated

**RE Zone Raster Locations**
- Test that the _AOI_WEE_score_ raster is correctly generated

**RE Point Locations**
- Test that the _POI_WEE_score_ raster is correctly generated

**Comment by mvmaltitz** [comment]
The following needs to be tested:

Set-up: 
![Image](https://github.com/user-attachments/assets/6a257468-521e-48e6-af78-65601907ed2a)

## 1. Contextual
**Workplace Discrimination:** 
- [ ] Test that the _WD_ raster is correctly generated
![Image](https://github.com/user-attachments/assets/a3d898bb-d0c1-4a66-8e83-00cbf6bc8d1f)
Score 2.5

**Regulatory Frameworks**
- [ ] Test that the _RF_ raster is correctly generated
![Image](https://github.com/user-attachments/assets/219322ea-0d65-4a7f-ba26-a5fdba5f6f6b)
Score 2.25

**Financial Inclusion**
- [ ] Test that the _FIN_ raster is correctly generated
![Image](https://github.com/user-attachments/assets/b1741bcc-d3ea-40ad-9b10-051dec4d2bae)
Score: 2,5

**Aggregate**
- [ ] Test that the _Contextual_score_ raster is correctly generated
![Image](https://github.com/user-attachments/assets/202a1557-8b48-4438-9894-990e32ef5ab4)

## 2. Accessibility
**Woman's Travel Patterns**
- [ ] Test that the _Green Spaces_ raster is correctly generated
- [ ] Test that the _Grocery Stores_ raster is correctly generated
- [ ] Test that the _Pharmacies_ raster is correctly generated
- [ ] Test that the _Kindergaten or Primary Schools_ raster is correctly generated
- [ ] Test that the _WTP_ raster is correctly generated

**Public Transport**
- [ ] Test that the _PBT_ raster is correctly generated

**Education and Training Facilities**
- [ ] Test that the _EFT_ raster is correctly generated

**Health Facilities**
- [ ] Test that the _HEF_ raster is correctly generated

**Financial Facilities**
- [ ] Test that the _FIF_ raster is correctly generated

**Aggregate**
- [ ] Test that the _Accessibility_score_ raster is correctly generated

## 3. Place Characterization
**Active Transport**
- [ ] Test that the _Crosswalks_ raster is correctly generated
- [ ] Test that the _Cycle Paths_ raster is correctly generated
- [ ] Test that the _Pathways_ raster is correctly generated
- [ ] Test that the _Block_ raster is correctly generated
- [ ] Test that the _AT_ raster is correctly generated

**Safety**
- [ ] Test that the _SAF_ raster is correctly generated using a point input
- [ ] Test that the _SAF_ raster is correctly generated using a polygon input
- [ ] Test that the _SAF_ raster is correctly generated using a raster input
- [ ] Test that the _SAF_ raster is correctly generated using a perceived safety value input

**Digital Inclusion**
- [ ] Test that the _DIG_ raster is correctly generated using the field of interest option
- [ ] Test that the _DIG_ raster is correctly generated using an internet access value

**Environmental Hazards**
- [ ] Test that the _Fire_ raster is correctly generated
- [ ] Test that the _Flood_ raster is correctly generated
- [ ] Test that the _Landslide_ raster is correctly generated
- [ ] Test that the _Tropical Cyclone_ raster is correctly generated
- [ ] Test that the _Drought_ raster is correctly generated
- [ ] Test that the _ENV_ raster is correctly generated

**Education**
- [ ] Test that the _EDU_ raster is correctly generated using the field of interest option
- [ ] Test that the _EDU_ raster is correctly generated using an education value

**FCV**
- [ ] Test that the _FCV_ raster is correctly generated using just the CSV input file with no impact radius
- [ ] Test that the _FCV_ raster is correctly generated using the CSV input file with impact radius

**Water Sanitation**
- [ ] Test that the _WAS_ raster is correctly generated 

**Aggregate**
- [ ] Test that the _Place_score_ raster is correctly generated

## 4. Aggregate
- [ ] Test that the _WEE_ raster is correctly generated

## 5. Insights
**Enablement**
- [ ] Test that the _WEE_pop_adm_score_ raster is correctly generated

**RE Zone Raster Locations**
- [ ] Test that the _AOI_WEE_score_ raster is correctly generated

**RE Point Locations**
- [ ] Test that the _POI_WEE_score_ raster is correctly generated

**Comment by osundwajeff** [comment]
Thanks @mvmaltitz I will look into the issues

**Comment by osundwajeff** [comment]
@mvmaltitz 
SAF raster:
![image](https://github.com/user-attachments/assets/3cf0c455-9738-42de-9ed5-3f8bcdbd3417)

Output:
![image](https://github.com/user-attachments/assets/afcbb903-fe76-470e-88ae-a93661851937)

**Comment by osundwajeff** [comment]
For ENV -> Landslides:

![Image](https://github.com/user-attachments/assets/0009d5e0-11fa-4406-ad11-ae117e62f923)

I'm not able to replicate the issue

**Comment by osundwajeff** [comment]
For ENV -> Drought:

![Image](https://github.com/user-attachments/assets/9dd9d901-b520-406a-9f9b-2af36d177391)

No `nodata` values.

**Comment by osundwajeff** [comment]
For ENV aggregation:

![Image](https://github.com/user-attachments/assets/6de2689a-b040-4a50-a713-75b862495081)

All good.

**Comment by bennyistanto** [comment]
@mvmaltitz in your picture above, you mention some No Data value. It because you are using the low resolution boundary from World Bank. And it also divided into two files, East and West.

For Fiji, please use the data that I have compiled, Link: https://drive.google.com/file/d/1-3UpliiCotIfNoTtB6_CmQoBjrj6z6bX/view?usp=sharing and the boundary using the latest from HDX.
