### ISSUE TITLE
Factor: Regulatory Frameworks

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST#37]
Check and ensure that we have unit tests, implementation and verified results for this indicator

![image](https://github.com/kartoza/GEEST/assets/178003/f9bc5913-20d9-45cb-a5c8-24a0af153464)

**Comment by carolinamayh** [comment]
All the factors in the Contextual Dimension are sourced from the Women, Business, and the Law database, which provides scores ranging from 0 to 100, with 100 being the highest possible score. The Regulatory Frameworks score is obtained from the average of the Pay and Parenthood indexes. The user should be able to input both scores, and the tool would calculate the average, standardize it to a scale from 0 to 5, and apply it to the entire country.

**Comment by carolinamayh** [comment]
I do not understand why a whole day of work is needed if the Contextual Dimension factors have no spatial variability within a country and only represent a single score for the entire nation. The user should be able to add this score, which is on a scale from 0 to 100, and it should be standardized to a scale from 0 to 5 and assigned to the entire territory.

In addition, the Workplace Discrimination factor needs to be incorporated into the Contextual Dimension. The methodology for this inclusion will follow the same approach as that used for the other two Contextual factors.

**Comment by dragosgontariu** [comment]
error encountered:

Could not create layer D:/Munca/WB/Geest/St_Lucia/Testing/07082024/temp/countryBuff.shp: Creation of layer failed (OGR error: Failed to create file D:/Munca/WB/Geest/St_Lucia/Testing/07082024/temp\countryBuff.shp: No such file or directory)

@osundwajeff @mvmaltitz @javaftw

**Comment by mvmaltitz** [comment]
Input and result:


![Image](https://github.com/user-attachments/assets/938a4c98-1b4b-4a5e-8f92-f933315ff7bb)

**Comment by mvmaltitz** [comment]
### Test Results

### Data
Link: https://drive.google.com/file/d/1-3UpliiCotIfNoTtB6_CmQoBjrj6z6bX/view?usp=sharing
All data has been converted into EPSG:8859

### Contextual

Each Factors in Contextual Dimension completed. 

![Screenshot 2024-09-12 190112](https://github.com/user-attachments/assets/9520b8b0-1679-49bf-a5cc-0d1ce345d3ee)
![Screenshot 2024-09-12 190406](https://github.com/user-attachments/assets/701ad3c1-ac72-41b9-a5c9-09699d5a1cca)
![Screenshot 2024-09-12 190544](https://github.com/user-attachments/assets/b88145c8-6036-4939-bc98-b3ea1cf725a5)

Contextual_score also succeed with some Python error. Although the Contextual_score.tif exist but the value is incorrect, then it means the script failed to generate the correct value and save as a file.

```
2024-09-12T19:06:09     WARNING    Traceback (most recent call last):
              File "C:\Users/benny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 6009, in contextual_aggregation
              with rasterio.open(aggregation, "w", **meta1) as dst:
              File "C:\Users\benny\AppData\Roaming\Python\Python39\site-packages\rasterio\env.py", line 451, in wrapper
              return f(*args, **kwds)
              File "C:\Users\benny\AppData\Roaming\Python\Python39\site-packages\rasterio\__init__.py", line 341, in open
              dataset = writer(
              File "rasterio\\_io.pyx", line 1464, in rasterio._io.DatasetWriterBase.__init__
              File "rasterio\\_io.pyx", line 330, in rasterio._io._delete_dataset_if_exists
              File "rasterio\\_err.pyx", line 195, in rasterio._err.exc_wrap_int
             rasterio._err.CPLE_AppDefinedError: Deleting Contextual_score.tif failed: Permission denied
```

See ticket #134 and #135 for more full testing results
