### ISSUE TITLE
Factor: Active Transport- Subfactor: Location of footpaths (OSM)

### ISSUE THREAD

**Issue by amyburness** [kartoza/GEEST#47]
````
[out:xml] [timeout:25];
 {{geocodeArea:Saint Lucia}} -> .area_0;
(
    node["highway"="footway"](area.area_0);
    way["highway"="footway"](area.area_0);
    relation["highway"="footway"](area.area_0);
);
(._;>;);
out body;
````
This indicator is composed by calculating the average of these four factors. First, the territory needs to be divided into 100m x 100m rasters.
3. Footpaths (measured by availability/presence per raster)
•	0: No footpaths
•	3: 1 footpath 
•	5: 2 or more footpaths

**Comment by carolinamayh** [comment]
Similar to Women's Travel Patterns, Active Transport is assessed by evaluating several subfactors, including the location of footpaths. The final score for Active Transport should be the average of the subfactor scores per raster. The tool's interface should not include separate tabs for each subfactor. Please note that the methodology and name for this specific factor, Active Transport, were incorrect in the first version of the GEEST. @osundwajeff

**Comment by mvmaltitz** [comment]
Footpaths result:


![Image](https://github.com/user-attachments/assets/0567f95d-f2a9-4e4b-8472-918035bed350)



![Image](https://github.com/user-attachments/assets/72ef8cb4-5d9b-45db-a8c7-bedd32c641af)

@dragosgontariu

**Comment by dragosgontariu** [comment]
#42
