### ISSUE TITLE
Factor: Digital Inclusion - Individuals using the Internet (% of population)

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST#51]
Reclassify input data to a standardized scale of 0 to 5 using a linear scaling process, such that 5 represents areas where 100% of houses have Internet access, and 0 represents areas where no houses have Internet access. Users should have the option to upload disaggregated data at various administrative levels or at the country level.

Source: WorldBank

**Comment by ClaraIV** [comment]
no change required for this factor, you can close/delete ticket. @osundwajeff

**Comment by carolinamayh** [comment]
The change in this factor is that currently, users need to input the scores associated with administrative boundaries. This method is appropriate if users have disaggregated scores at, for example, the municipal or district level. However, if users only have a score at the country level, similar to the Contextual factors, they should be able to input the number directly. The tool will then standardize this score on a scale from 0 to 5 and assign it to the entire territory. @osundwajeff

**Comment by dragosgontariu** [comment]
the only option working is that with user input value but not the polygon user input data. please fix it.

furthermore when the user utilizes one option the other one should not be working - it is confusing which input the tool consumes.

@osundwajeff @mvmaltitz

**Comment by mvmaltitz** [comment]
Results
Admin boundary - Internet Access Value = 50


![Image](https://github.com/user-attachments/assets/598cd9c7-9fbf-43c5-904d-f9ca7b19badb)

Smaller boundary areas


![Image](https://github.com/user-attachments/assets/0bea2344-4a57-4744-8726-e4e7a679b75a)



@dragosgontariu
