### ISSUE TITLE
Factor: Education - percentage of the labor force comprising women with university degrees in specified fields

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST#54]
Source:  Central Statistics Office/Humdata

Reclassify the input data to a standardized scale from 0 to 5 using a linear scaling process. On this scale, a score of 5 represents areas where all women have a university (STEM) degree, while a score of 0 represents areas where no women have a university degree. Users should have the option to upload disaggregated data at various administrative levels or at the country level.

**Comment by ClaraIV** [comment]
the action required for this indicator is to be moved into the Contextual Tab.

**Comment by carolinamayh** [comment]
This factor was originally part of the Individual Dimension. Since this dimension has been removed, it should now be included in the Place-Characterization Dimension. @osundwajeff

**Comment by ClaraIV** [comment]
@osundwajeff  if users only have a score at the country level, similar to the Contextual factors, they should be able to input the number directly. The tool will then standardize this score on a scale from 0 to 5 and assign it to the entire territory.

**Comment by dragosgontariu** [comment]
missing: there is no user input field for education level as per specifications; see screenshot below and the one for digital inclusion for example

![Image](https://github.com/user-attachments/assets/d9cf548c-ea4a-4012-a501-39686abe02e3)



![Image](https://github.com/user-attachments/assets/13c682a0-a753-4bfa-8e17-31d69590e418)


@osundwajeff @javaftw

**Comment by javaftw** [comment]
@dragosgontariu Hi Dragos, could you please either provide the input data, or direct me to where to find it, for testing `Factor:Education`

**Comment by dragosgontariu** [comment]
Hi @javaftw 

You can find it at: https://data.worldbank.org/indicator/SL.TLF.ADVN.FE.ZS?locations=LC

For St.Lucia the value is 80 in 2022 as per the data found there.

**Comment by javaftw** [comment]
**Input: User Value**

![Image](https://github.com/user-attachments/assets/8b7ca5f3-d521-4d48-98e9-262f4d7fd148)

**Comment by mvmaltitz** [comment]
Results: 
Admin boundary - Education level value = 50%


![Image](https://github.com/user-attachments/assets/c6fe9551-20ce-4f05-881b-04d310f9f5f4)

Smaller boundaries


![Image](https://github.com/user-attachments/assets/d0dcf06f-f7ad-4558-96d5-9c33d692cd7c)

@dragosgontariu

**Comment by dragosgontariu** [comment]
@osundwajeff @mvmaltitz @javaftw 
the input value of 80 resulted into 0 score:



![Image](https://github.com/user-attachments/assets/c7800c2f-cec1-495c-afc2-47b262cac7b9)

**Comment by mvmaltitz** [comment]
@dragosgontariu 
This has been fixes

![Image](https://github.com/user-attachments/assets/7a7f3221-3d62-42bd-ba36-0ba318bc1a70)
