### ISSUE TITLE
Factor: FCV - ACLED data (Violence Estimated Events)

### ISSUE THREAD

**Issue by amyburness** [kartoza/GEEST#55]
This indicator should be structured by assigning scores to rasters based on their overlap with buffers indicating different types of events. Using point locations of FCV events, generate circular buffers with a radius of 5 km to estimate the spatial impact of these events. If the impact radius of an event is known, it should be used instead. Any raster intersecting with the buffer should be scored as follows:
•	Rasters overlapping with buffers indicating battles and explosions: score 0
•	Rasters overlapping with buffers indicating explosions and remote violence: score 1
•	Rasters overlapping with buffers indicating violence against civilians: score 2
•	Rasters overlapping with buffers indicating protests and riots: score 4
•	Areas that do not overlap with any event: score 5

Adjustments are needed as it is currently evaluated differently.

WB team will provide the ACLED data for St Lucia

**Comment by osundwajeff** [comment]
Hi @ClaraIV is there any more information you would like to add on this ticket?

**Comment by osundwajeff** [comment]
Hi @dragosgontariu, @carolinamayh , @ClaraIV
the ACLED data is in csv format. I wanted to confirm with you if this factor would use the csv as an input or it will use the ACLED as a shapefile?

**Comment by ClaraIV** [comment]
hi Jeff,

Good question, I guess it would be good to have the input as .csv, given
that every export from ACLED is csv format.

Thanks for checking with us,
Clara

**Comment by osundwajeff** [comment]
Hi @ClaraIV, I wanted to confirm which specific rasters are these that will overlap with the buffers? I'd really appreciate if you can provide more context on that.

**Comment by ClaraIV** [comment]
hi @osundwajeff  thanks for raising this issue; I think we didnt explain properly, apologies for that. what we mean is raster cells. We need to create a raster with cell values from 0-5, where the cells that intersect any of the buffers from the events, take the score as per the table below. If a cell intersect more types of events, it will take the score of the more serious event, as in the classification below.

5km buffer from event points

• Raster cells overlapping with buffers indicating battles and explosions: score 0
• Raster cells overlapping with buffers indicating explosions and remote violence: score 1
• Raster cells overlapping with buffers indicating violence against civilians: score 2
• Raster cells overlapping with buffers indicating protests and riots: score 4
• Raster cells that do not overlap with any event: score 5

Please let me know if everything is clear, or you have more questions - thanks!

**Comment by osundwajeff** [comment]
Thanks @ClaraIV. I think I now understand it well enough.
If I have any further questions I'll just ask.

**Comment by dragosgontariu** [comment]
error encountered:

 Traceback (most recent call last):
              File "fiona\_shim.pyx", line 83, in fiona._shim.gdal_open_vector
              File "fiona\_err.pyx", line 291, in fiona._err.exc_wrap_pointer
             fiona._err.CPLE_OpenFailedError: D:/Munca/WB/Geest/St_Lucia/Testing/07082024/temp/acled.shp: No such file or directory
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 345, in 
              self.dlg.FCV_Execute_PB.clicked.connect(lambda: self.Rasterize(6))
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 1272, in Rasterize
              self.convertCRS(csvFileLayer, UTM_crs)
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 607, in convertCRS
              shp = gpd.read_file(vector)
              File "C:\Users\Dragos\AppData\Roaming\Python\Python39\site-packages\geopandas\io\file.py", line 289, in _read_file
              return _read_file_fiona(
              File "C:\Users\Dragos\AppData\Roaming\Python\Python39\site-packages\geopandas\io\file.py", line 315, in _read_file_fiona
              with reader(path_or_bytes, **kwargs) as features:
              File "C:\Users\Dragos\AppData\Roaming\Python\Python39\site-packages\fiona\env.py", line 408, in wrapper
              return f(*args, **kwargs)
              File "C:\Users\Dragos\AppData\Roaming\Python\Python39\site-packages\fiona\__init__.py", line 286, in open
              c = Collection(path, mode, driver=driver, encoding=encoding,
              File "C:\Users\Dragos\AppData\Roaming\Python\Python39\site-packages\fiona\collection.py", line 162, in __init__
              self.session.start(self, **kwargs)
              File "fiona\ogrext.pyx", line 540, in fiona.ogrext.Session.start
              File "fiona\_shim.pyx", line 90, in fiona._shim.gdal_open_vector
             fiona.errors.DriverError: D:/Munca/WB/Geest/St_Lucia/Testing/07082024/temp/acled.shp: No such file or directory
             

@osundwajeff @mvmaltitz

**Comment by mvmaltitz** [comment]
FCV Result:


![Image](https://github.com/user-attachments/assets/e9f03bae-21b8-4b1f-9134-ba4ae01c94b9)

@dragosgontariu

**Comment by bennyistanto** [comment]
Similar to [Active Transport](https://github.com/kartoza/GEEST/issues/42#issuecomment-2334237593), I managed to test using Tunisia data, unfortunately the FCV failed without any error information, it just Not Responding (see attached picture below) after I clicked the Execute button and the label "Processing..." appear. I have tried it on two machines with the same result.

![Screenshot 2024-09-06 094243](https://github.com/user-attachments/assets/b7b65439-166f-4bd1-bd79-35838e734358)

Data for test: 
[FCV_Tunisia.csv](https://github.com/user-attachments/files/16910724/FCV_Tunisia.csv)

**Comment by osundwajeff** [comment]
Hi @bennyistanto
Can you assist me with FCV data for Fiji, I have modified a couple of things on FCv and I need to test using that dataset

**Comment by dragosgontariu** [comment]
Hi @osundwajeff 
Below you can find FCV data for Fiji
[2019-09-01-2024-09-01-Fiji.csv](https://github.com/user-attachments/files/16937817/2019-09-01-2024-09-01-Fiji.csv)

**Comment by osundwajeff** [comment]
Hi @dragosgontariu
Thanks.
