### ISSUE TITLE
Tunisia - Place Characterization aggregation

### ISSUE THREAD

**Issue by dragosgontariu** [kartoza/GEEST#60]
Hi Jeff ,

It seems that I also have problems when I want to send emails.

Please let me know if you have received this?

[Place Characterization.zip](https://github.com/user-attachments/files/15969977/Place.Characterization.zip)

____________________________________________________

Sorry, we were unable to deliver your message to the following address.

<[jeff@kartoza.com](mailto:jeff@kartoza.com)>:
552: 5.7.0 This message was blocked because its content presents a potential
5.7.0 security issue. To review our message content and attachment content
5.7.0 guidelines, go to
5.7.0  https://support.google.com/mail/?p=BlockedMessage d75a77b69052e-444fbb5ceb8si5408711cf.87 - gsmtp

____________________________________________________

Hi Jeff,
1.
I’m reaching out to ask for your assistance with the aggregation process for the Place Characterization factors. I'm encountering an error with the WLK raster, which seems to be causing some issues. Here is the error message I'm receiving:

 Traceback (most recent call last):
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 4024, in placeCharacterizationAggregation
              (WLK_ras * WLK_weight / 100)
             ValueError: operands could not be broadcast together with shapes (8152,3857) (8153,3857) 

![Image](https://github.com/kartoza/GEEST/assets/161034767/838059de-4279-4242-90e5-c26f232f0abc)

To help diagnose the problem, I have attached you the rest of the output rasters here.

2. 
Otherwise, if I'm trying to skip the Active Transport I'm getting this:

![Image](https://github.com/kartoza/GEEST/assets/161034767/645fb478-2fbf-4a99-a1b4-a27e87134c49)

We need the aggregated rasters as per the new tool factors.

My best,
Dragos

**Comment by mvmaltitz** [comment]
Ticket addressed by #113
