### ISSUE TITLE
Rename output files

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/GEEST#75]
The output files dont have a consistent and always intuitive naming. We have defined the below nomenclature for all output files, grateful if you could update. We'll send the excel file via email as well.

![Image](https://github.com/user-attachments/assets/e22a9726-8ffd-424e-b4d9-0d07e06e05ae)

**Comment by ClaraIV** [comment]
linked to #40 #41 #44 #43 #39 #42 @osundwajeff  please see above, we have refined the nomenclature for all outputs and the specification in these tickets changed. Please follow the guidance above, and you can close the tickets when fixed as per the above. thanks!

**Comment by javaftw** [comment]
Review 29 Jul 2024:

Input:


![Image](https://github.com/user-attachments/assets/c08144d4-95a6-496c-a4f2-fb5c64cba77d)


Output file naming:


![Image](https://github.com/user-attachments/assets/d2a8b741-bb49-4a81-87fa-009e89f2f924)
